auto_detect_range: false
auto_detect_phi: false
auto_detect_theta: false
auto_detect_width_height: false
model:
  range_min: 0.5
  range_max: 130.0
  phi_min: -0.261799067259
  phi_inc: 0.03490658503988659
  phi_N: 16
  theta_min: -3.14159011841
  theta_inc: 0.0034447287868309136 # (2*pi)/1823 instead of (2*pi)/1824 ? is this correct (2*pi)/1824 ?
  theta_N: 1824
  